### ISSUE TITLE
error:You cannot directly instantiate an STPIssuingCardPin deserializer:[STPIssuingCardPin new]

### ISSUE THREAD

**Issue by wytex** [jonasbark/flutter_stripe_payment#288] opened 2021-04-29 11:56 UTC
I can't build iOS Flutter app due to this error:
`You cannot directly instantiate an STPIssuingCardPin
                                                    deserializer:[STPIssuingCardPin new]`
                                                    
here is my podfile.lock

```
PODS:
  - abseil/algorithm (0.20200225.0):
    - abseil/algorithm/algorithm (= 0.20200225.0)
    - abseil/algorithm/container (= 0.20200225.0)
  - abseil/algorithm/algorithm (0.20200225.0):
    - abseil/base/config
  - abseil/algorithm/container (0.20200225.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/base (0.20200225.0):
    - abseil/base/atomic_hook (= 0.20200225.0)
    - abseil/base/base (= 0.20200225.0)
    - abseil/base/base_internal (= 0.20200225.0)
    - abseil/base/bits (= 0.20200225.0)
    - abseil/base/config (= 0.20200225.0)
    - abseil/base/core_headers (= 0.20200225.0)
    - abseil/base/dynamic_annotations (= 0.20200225.0)
    - abseil/base/endian (= 0.20200225.0)
    - abseil/base/errno_saver (= 0.20200225.0)
    - abseil/base/exponential_biased (= 0.20200225.0)
    - abseil/base/log_severity (= 0.20200225.0)
    - abseil/base/malloc_internal (= 0.20200225.0)
    - abseil/base/periodic_sampler (= 0.20200225.0)
    - abseil/base/pretty_function (= 0.20200225.0)
    - abseil/base/raw_logging_internal (= 0.20200225.0)
    - abseil/base/spinlock_wait (= 0.20200225.0)
    - abseil/base/throw_delegate (= 0.20200225.0)
  - abseil/base/atomic_hook (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/base (0.20200225.0):
    - abseil/base/atomic_hook
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/log_severity
    - abseil/base/raw_logging_internal
    - abseil/base/spinlock_wait
    - abseil/meta/type_traits
  - abseil/base/base_internal (0.20200225.0):
    - abseil/base/config
    - abseil/meta/type_traits
  - abseil/base/bits (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/config (0.20200225.0)
  - abseil/base/core_headers (0.20200225.0):
    - abseil/base/config
  - abseil/base/dynamic_annotations (0.20200225.0)
  - abseil/base/endian (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/errno_saver (0.20200225.0):
    - abseil/base/config
  - abseil/base/exponential_biased (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/log_severity (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/malloc_internal (0.20200225.0):
    - abseil/base/base
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/raw_logging_internal
  - abseil/base/periodic_sampler (0.20200225.0):
    - abseil/base/core_headers
    - abseil/base/exponential_biased
  - abseil/base/pretty_function (0.20200225.0)
  - abseil/base/raw_logging_internal (0.20200225.0):
    - abseil/base/atomic_hook
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/log_severity
  - abseil/base/spinlock_wait (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/core_headers
    - abseil/base/errno_saver
  - abseil/base/throw_delegate (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/container/compressed_tuple (0.20200225.0):
    - abseil/utility/utility
  - abseil/container/inlined_vector (0.20200225.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/base/throw_delegate
    - abseil/container/inlined_vector_internal
    - abseil/memory/memory
  - abseil/container/inlined_vector_internal (0.20200225.0):
    - abseil/base/core_headers
    - abseil/container/compressed_tuple
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/types/span
  - abseil/memory (0.20200225.0):
    - abseil/memory/memory (= 0.20200225.0)
  - abseil/memory/memory (0.20200225.0):
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/meta (0.20200225.0):
    - abseil/meta/type_traits (= 0.20200225.0)
  - abseil/meta/type_traits (0.20200225.0):
    - abseil/base/config
  - abseil/numeric/int128 (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/strings/internal (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/meta/type_traits
  - abseil/strings/str_format (0.20200225.0):
    - abseil/strings/str_format_internal
  - abseil/strings/str_format_internal (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/numeric/int128
    - abseil/strings/strings
    - abseil/types/span
  - abseil/strings/strings (0.20200225.0):
    - abseil/base/base
    - abseil/base/bits
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/base/throw_delegate
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/numeric/int128
    - abseil/strings/internal
  - abseil/time (0.20200225.0):
    - abseil/time/internal (= 0.20200225.0)
    - abseil/time/time (= 0.20200225.0)
  - abseil/time/internal (0.20200225.0):
    - abseil/time/internal/cctz (= 0.20200225.0)
  - abseil/time/internal/cctz (0.20200225.0):
    - abseil/time/internal/cctz/civil_time (= 0.20200225.0)
    - abseil/time/internal/cctz/time_zone (= 0.20200225.0)
  - abseil/time/internal/cctz/civil_time (0.20200225.0):
    - abseil/base/config
  - abseil/time/internal/cctz/time_zone (0.20200225.0):
    - abseil/base/config
    - abseil/time/internal/cctz/civil_time
  - abseil/time/time (0.20200225.0):
    - abseil/base/base
    - abseil/base/core_headers
    - abseil/base/raw_logging_internal
    - abseil/numeric/int128
    - abseil/strings/strings
    - abseil/time/internal/cctz/civil_time
    - abseil/time/internal/cctz/time_zone
  - abseil/types (0.20200225.0):
    - abseil/types/any (= 0.20200225.0)
    - abseil/types/bad_any_cast (= 0.20200225.0)
    - abseil/types/bad_any_cast_impl (= 0.20200225.0)
    - abseil/types/bad_optional_access (= 0.20200225.0)
    - abseil/types/bad_variant_access (= 0.20200225.0)
    - abseil/types/compare (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - abseil/types/span (= 0.20200225.0)
    - abseil/types/variant (= 0.20200225.0)
  - abseil/types/any (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/types/bad_any_cast
    - abseil/utility/utility
  - abseil/types/bad_any_cast (0.20200225.0):
    - abseil/base/config
    - abseil/types/bad_any_cast_impl
  - abseil/types/bad_any_cast_impl (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/bad_optional_access (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/bad_variant_access (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/compare (0.20200225.0):
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/types/optional (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/types/bad_optional_access
    - abseil/utility/utility
  - abseil/types/span (0.20200225.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/base/throw_delegate
    - abseil/meta/type_traits
  - abseil/types/variant (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/types/bad_variant_access
    - abseil/utility/utility
  - abseil/utility/utility (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/meta/type_traits
  - agora_rtc_engine (3.3.2):
    - AgoraRtcEngine_iOS (= 3.3.1)
    - Flutter
  - AgoraRtcEngine_iOS (3.3.1)
  - "app_settings (3.0.0+1)":
    - Flutter
  - BoringSSL-GRPC (0.0.7):
    - BoringSSL-GRPC/Implementation (= 0.0.7)
    - BoringSSL-GRPC/Interface (= 0.0.7)
  - BoringSSL-GRPC/Implementation (0.0.7):
    - BoringSSL-GRPC/Interface (= 0.0.7)
  - BoringSSL-GRPC/Interface (0.0.7)
  - cloud_firestore (0.14.4):
    - Firebase/CoreOnly (~> 6.33.0)
    - Firebase/Firestore (~> 6.33.0)
    - firebase_core
    - Flutter
  - Firebase/Analytics (6.33.0):
    - Firebase/Core
  - Firebase/Auth (6.33.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.9.2)
  - Firebase/Core (6.33.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.8.3)
  - Firebase/CoreOnly (6.33.0):
    - FirebaseCore (= 6.10.3)
  - Firebase/Database (6.33.0):
    - Firebase/CoreOnly
    - FirebaseDatabase (~> 6.6.0)
  - Firebase/Firestore (6.33.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 1.18.0)
  - Firebase/Messaging (6.33.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.7.0)
  - Firebase/Storage (6.33.0):
    - Firebase/CoreOnly
    - FirebaseStorage (~> 3.9.0)
  - firebase_auth (0.18.4-1):
    - Firebase/Auth (~> 6.33.0)
    - Firebase/CoreOnly (~> 6.33.0)
    - firebase_core
    - Flutter
  - firebase_core (0.5.3):
    - Firebase/CoreOnly (~> 6.33.0)
    - Flutter
  - firebase_database (4.4.0):
    - Firebase/CoreOnly (~> 6.33.0)
    - Firebase/Database (~> 6.33.0)
    - firebase_core
    - Flutter
  - firebase_messaging (7.0.3):
    - Firebase/CoreOnly (~> 6.33.0)
    - Firebase/Messaging (~> 6.33.0)
    - firebase_core
    - Flutter
  - firebase_storage (5.0.1):
    - Firebase/CoreOnly (~> 6.33.0)
    - Firebase/Storage (~> 6.33.0)
    - firebase_core
    - Flutter
  - FirebaseAnalytics (6.8.3):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleAppMeasurement (= 6.8.3)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - FirebaseAuth (6.9.2):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/Environment (~> 6.7)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (6.10.3):
    - FirebaseCoreDiagnostics (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
  - FirebaseCoreDiagnostics (1.7.0):
    - GoogleDataTransport (~> 7.4)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30906.0)
  - FirebaseDatabase (6.6.0):
    - FirebaseCore (~> 6.10)
    - leveldb-library (~> 1.22)
  - FirebaseFirestore (1.18.0):
    - abseil/algorithm (= 0.20200225.0)
    - abseil/base (= 0.20200225.0)
    - abseil/memory (= 0.20200225.0)
    - abseil/meta (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/time (= 0.20200225.0)
    - abseil/types (= 0.20200225.0)
    - FirebaseCore (~> 6.10)
    - "gRPC-C++ (~> 1.28.0)"
    - leveldb-library (~> 1.22)
    - nanopb (~> 1.30906.0)
  - FirebaseInstallations (1.7.0):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.8.0):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
  - FirebaseMessaging (4.7.1):
    - FirebaseCore (~> 6.10)
    - FirebaseInstanceID (~> 4.7)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Reachability (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - FirebaseStorage (3.9.1):
    - FirebaseCore (~> 6.10)
    - GTMSessionFetcher/Core (~> 1.1)
  - Flutter (1.0.0)
  - flutter_email_sender (0.0.1):
    - Flutter
  - flutter_local_notifications (0.0.1):
    - Flutter
  - flutter_ringtone_player (0.0.1):
    - Flutter
  - flutter_statusbarcolor (0.0.1):
    - Flutter
  - FMDB (2.7.5):
    - FMDB/standard (= 2.7.5)
  - FMDB/standard (2.7.5)
  - GoogleAppMeasurement (6.8.3):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - GoogleDataTransport (7.5.1):
    - nanopb (~> 1.30906.0)
  - GoogleUtilities/AppDelegateSwizzler (6.7.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.7.2):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.7.2):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.7.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.7.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.7.2)"
  - GoogleUtilities/Reachability (6.7.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.7.2):
    - GoogleUtilities/Logger
  - "gRPC-C++ (1.28.2)":
    - "gRPC-C++/Implementation (= 1.28.2)"
    - "gRPC-C++/Interface (= 1.28.2)"
  - "gRPC-C++/Implementation (1.28.2)":
    - abseil/container/inlined_vector (= 0.20200225.0)
    - abseil/memory/memory (= 0.20200225.0)
    - abseil/strings/str_format (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - "gRPC-C++/Interface (= 1.28.2)"
    - gRPC-Core (= 1.28.2)
  - "gRPC-C++/Interface (1.28.2)"
  - gRPC-Core (1.28.2):
    - gRPC-Core/Implementation (= 1.28.2)
    - gRPC-Core/Interface (= 1.28.2)
  - gRPC-Core/Implementation (1.28.2):
    - abseil/container/inlined_vector (= 0.20200225.0)
    - abseil/memory/memory (= 0.20200225.0)
    - abseil/strings/str_format (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - BoringSSL-GRPC (= 0.0.7)
    - gRPC-Core/Interface (= 1.28.2)
  - gRPC-Core/Interface (1.28.2)
  - GTMSessionFetcher/Core (1.5.0)
  - image_picker (0.0.1):
    - Flutter
  - integration_test (0.0.1):
    - Flutter
  - leveldb-library (1.22)
  - nanopb (1.30906.0):
    - nanopb/decode (= 1.30906.0)
    - nanopb/encode (= 1.30906.0)
  - nanopb/decode (1.30906.0)
  - nanopb/encode (1.30906.0)
  - notification_permissions (0.4.4):
    - Flutter
  - open_file (0.0.1):
    - Flutter
  - path_provider (0.0.1):
    - Flutter
  - "permission_handler (5.1.0+2)":
    - Flutter
  - PromisesObjC (1.2.12)
  - Protobuf (3.14.0)
  - share (0.0.1):
    - Flutter
  - shared_preferences (0.0.1):
    - Flutter
  - sqflite (0.0.2):
    - Flutter
    - FMDB (>= 2.7.5)
  - Stripe (19.4.0)
  - stripe_payment (1.0.0):
    - Flutter
    - Stripe (~> 19.4.0)
  - url_launcher (0.0.1):
    - Flutter
  - video_player (0.0.1):
    - Flutter
  - webview_flutter (0.0.1):
    - Flutter

DEPENDENCIES:
  - agora_rtc_engine (from `.symlinks/plugins/agora_rtc_engine/ios`)
  - app_settings (from `.symlinks/plugins/app_settings/ios`)
  - cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`)
  - Firebase/Analytics
  - firebase_auth (from `.symlinks/plugins/firebase_auth/ios`)
  - firebase_core (from `.symlinks/plugins/firebase_core/ios`)
  - firebase_database (from `.symlinks/plugins/firebase_database/ios`)
  - firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`)
  - firebase_storage (from `.symlinks/plugins/firebase_storage/ios`)
  - Flutter (from `Flutter`)
  - flutter_email_sender (from `.symlinks/plugins/flutter_email_sender/ios`)
  - flutter_local_notifications (from `.symlinks/plugins/flutter_local_notifications/ios`)
  - flutter_ringtone_player (from `.symlinks/plugins/flutter_ringtone_player/ios`)
  - flutter_statusbarcolor (from `.symlinks/plugins/flutter_statusbarcolor/ios`)
  - image_picker (from `.symlinks/plugins/image_picker/ios`)
  - integration_test (from `.symlinks/plugins/integration_test/ios`)
  - notification_permissions (from `.symlinks/plugins/notification_permissions/ios`)
  - open_file (from `.symlinks/plugins/open_file/ios`)
  - path_provider (from `.symlinks/plugins/path_provider/ios`)
  - permission_handler (from `.symlinks/plugins/permission_handler/ios`)
  - share (from `.symlinks/plugins/share/ios`)
  - shared_preferences (from `.symlinks/plugins/shared_preferences/ios`)
  - sqflite (from `.symlinks/plugins/sqflite/ios`)
  - stripe_payment (from `.symlinks/plugins/stripe_payment/ios`)
  - url_launcher (from `.symlinks/plugins/url_launcher/ios`)
  - video_player (from `.symlinks/plugins/video_player/ios`)
  - webview_flutter (from `.symlinks/plugins/webview_flutter/ios`)

SPEC REPOS:
  trunk:
    - abseil
    - AgoraRtcEngine_iOS
    - BoringSSL-GRPC
    - Firebase
    - FirebaseAnalytics
    - FirebaseAuth
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseDatabase
    - FirebaseFirestore
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging
    - FirebaseStorage
    - FMDB
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleUtilities
    - "gRPC-C++"
    - gRPC-Core
    - GTMSessionFetcher
    - leveldb-library
    - nanopb
    - PromisesObjC
    - Protobuf
    - Stripe

EXTERNAL SOURCES:
  agora_rtc_engine:
    :path: ".symlinks/plugins/agora_rtc_engine/ios"
  app_settings:
    :path: ".symlinks/plugins/app_settings/ios"
  cloud_firestore:
    :path: ".symlinks/plugins/cloud_firestore/ios"
  firebase_auth:
    :path: ".symlinks/plugins/firebase_auth/ios"
  firebase_core:
    :path: ".symlinks/plugins/firebase_core/ios"
  firebase_database:
    :path: ".symlinks/plugins/firebase_database/ios"
  firebase_messaging:
    :path: ".symlinks/plugins/firebase_messaging/ios"
  firebase_storage:
    :path: ".symlinks/plugins/firebase_storage/ios"
  Flutter:
    :path: Flutter
  flutter_email_sender:
    :path: ".symlinks/plugins/flutter_email_sender/ios"
  flutter_local_notifications:
    :path: ".symlinks/plugins/flutter_local_notifications/ios"
  flutter_ringtone_player:
    :path: ".symlinks/plugins/flutter_ringtone_player/ios"
  flutter_statusbarcolor:
    :path: ".symlinks/plugins/flutter_statusbarcolor/ios"
  image_picker:
    :path: ".symlinks/plugins/image_picker/ios"
  integration_test:
    :path: ".symlinks/plugins/integration_test/ios"
  notification_permissions:
    :path: ".symlinks/plugins/notification_permissions/ios"
  open_file:
    :path: ".symlinks/plugins/open_file/ios"
  path_provider:
    :path: ".symlinks/plugins/path_provider/ios"
  permission_handler:
    :path: ".symlinks/plugins/permission_handler/ios"
  share:
    :path: ".symlinks/plugins/share/ios"
  shared_preferences:
    :path: ".symlinks/plugins/shared_preferences/ios"
  sqflite:
    :path: ".symlinks/plugins/sqflite/ios"
  stripe_payment:
    :path: ".symlinks/plugins/stripe_payment/ios"
  url_launcher:
    :path: ".symlinks/plugins/url_launcher/ios"
  video_player:
    :path: ".symlinks/plugins/video_player/ios"
  webview_flutter:
    :path: ".symlinks/plugins/webview_flutter/ios"

SPEC CHECKSUMS:
  abseil: 6c8eb7892aefa08d929b39f9bb108e5367e3228f
  agora_rtc_engine: c9c05dc6054a793d6dba94a615117d5f1dd41472
  AgoraRtcEngine_iOS: 17e55feec1bde14adc30fd9d743332d1e7821b62
  app_settings: d103828c9f5d515c4df9ee754dabd443f7cedcf3
  BoringSSL-GRPC: 8edf627ee524575e2f8d19d56f068b448eea3879
  cloud_firestore: b8c0e15fa49dfff87c2817d288b577e5dca2df13
  Firebase: 8db6f2d1b2c5e2984efba4949a145875a8f65fe5
  firebase_auth: d5159db3873478d1ac839af7b10d2f831516136a
  firebase_core: 5d6a02f3d85acd5f8321c2d6d62877626a670659
  firebase_database: a3737781469b5275f899e04fcb0aa556f37e400a
  firebase_messaging: 0aea2cd5885b65e19ede58ee3507f485c992cc75
  firebase_storage: d5cf595245e1770ef7081b026f603771bf5dd547
  FirebaseAnalytics: 5dd088bd2e67bb9d13dbf792d1164ceaf3052193
  FirebaseAuth: c92d49ada7948d1a23466e3db17bc4c2039dddc3
  FirebaseCore: d889d9e12535b7f36ac8bfbf1713a0836a3012cd
  FirebaseCoreDiagnostics: 770ac5958e1372ce67959ae4b4f31d8e127c3ac1
  FirebaseDatabase: 13a865a4b85897462b930eb683bda8f52583713f
  FirebaseFirestore: adff4877869ca91a11250cc0989a6cd56bad163f
  FirebaseInstallations: 466c7b4d1f58fe16707693091da253726a731ed2
  FirebaseInstanceID: bd3ffc24367f901a43c063b36c640b345a4a5dd1
  FirebaseMessaging: 5eca4ef173de76253352511aafef774caa1cba2a
  FirebaseStorage: 15e0f15ef3c7fec3d1899d68623e47d4447066b4
  Flutter: 434fef37c0980e73bb6479ef766c45957d4b510c
  flutter_email_sender: 02d7443217d8c41483223627972bfdc09f74276b
  flutter_local_notifications: 0c0b1ae97e741e1521e4c1629a459d04b9aec743
  flutter_ringtone_player: 15eba85187230b87b2512f0e1b92225618bc03e7
  flutter_statusbarcolor: 8afb1071ed8c58be929f1e32b36c629771fd2259
  FMDB: 2ce00b547f966261cd18927a3ddb07cb6f3db82a
  GoogleAppMeasurement: 966e88df9d19c15715137bb2ddaf52373f111436
  GoogleDataTransport: f56af7caa4ed338dc8e138a5d7c5973e66440833
  GoogleUtilities: 7f2f5a07f888cdb145101d6042bc4422f57e70b3
  "gRPC-C++": 13d8ccef97d5c3c441b7e3c529ef28ebee86fad2
  gRPC-Core: 4afa11bfbedf7cdecd04de535a9e046893404ed5
  GTMSessionFetcher: b3503b20a988c4e20cc189aa798fd18220133f52
  image_picker: 9c3312491f862b28d21ecd8fdf0ee14e601b3f09
  integration_test: 6eb66a19f7104200dcfdd62bc0077e1b09686e4f
  leveldb-library: 55d93ee664b4007aac644a782d11da33fba316f7
  nanopb: 59317e09cf1f1a0af72f12af412d54edf52603fc
  notification_permissions: b74860c2967c1579243a675e63cd55e0ae75cef7
  open_file: 02eb5cb6b21264bd3a696876f5afbfb7ca4f4b7d
  path_provider: abfe2b5c733d04e238b0d8691db0cfd63a27a93c
  permission_handler: ccb20a9fad0ee9b1314a52b70b76b473c5f8dab0
  PromisesObjC: 3113f7f76903778cf4a0586bd1ab89329a0b7b97
  Protobuf: 0cde852566359049847168e51bd1c690e0f70056
  share: 0b2c3e82132f5888bccca3351c504d0003b3b410
  shared_preferences: af6bfa751691cdc24be3045c43ec037377ada40d
  sqflite: 6d358c025f5b867b29ed92fc697fd34924e11904
  Stripe: 92f1c73a9dbd3c54277ed06a1fea6e08f20414c6
  stripe_payment: 1cbe9c339c21b5ecf01035e80eea351067c67c56
  url_launcher: 6fef411d543ceb26efce54b05a0a40bfd74cbbef
  video_player: 9cc823b1d9da7e8427ee591e8438bfbcde500e6e
  webview_flutter: 9f491a9b5a66f2573946a389b2677987b0ff8c0b

PODFILE CHECKSUM: c11ecb9f78254f0cdf5bb82f798782df8db65e67

COCOAPODS: 1.10.1

```
I have tried all the ways but nothing can't build iOS APP

**Comment by jonasbark** [comment] 2021-04-29 14:23
duplicate of https://github.com/jonasbark/flutter_stripe_payment/issues/284

**Closed by jonasbark** 2021-04-29 14:23 UTC
