### ISSUE TITLE
Project crash after import

### ISSUE THREAD

**Issue by andreagr** [jonasbark/flutter_stripe_payment#6] opened 2018-06-08 17:11 UTC
I followed the instructions you provided for install, but i get this error from the log:

Execution failed for task ':stripe_payment:compileDebugKotlin'.

and a huge Stacktrace error:
java.lang.AbstractMethodError: org.jetbrains.kotlin.android.synthetic.AndroidExtensionPropertiesComponentContainerContributor.addDeclarations(Lorg/jetbrains/kotlin/container/StorageComponentContainer;Lorg/jetbrains/kotlin/resolve/TargetPlatform;)V
	at org.jetbrains.kotlin.frontend.di.InjectionKt.configureModule(injection.kt:56)
	at org.jetbrains.kotlin.frontend.di.InjectionKt.configureModule(injection.kt:72)
(...)

Do you have any idea how to fix this?

**Comment by dancingbannana** [comment] 2018-07-05 16:48
I have this same issue did you ever find a fix?

**Comment by dancingbannana** [comment] 2018-07-08 17:02
I figured it out: 
For some reason this causes the error for me In the build.gradle i had this dependency: 
"classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.2-4" that cause the error and removing it fixed it for me.

**Comment by tkhokhar25** [comment] 2018-07-25 15:20
I have the same issue but I don't have this "classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.2-4" dependency in my build.gradle. The app doesn't run, or when it does, the emulator shows that the app keeps stopping. I'm using Visual Studio, I don't know if it matters though.

**Comment by jonasbark** [comment] 2018-07-25 15:40
What's the crash reason when it "runs"?

**Comment by jonasbark** [comment] 2018-07-31 12:09
can you post the crash stacktrace?

**Comment by ashtonthomas** [comment] 2018-08-24 15:14
@tkhokhar25 @jonasbark: @thmsdnnr and I are seeing the same crash on start-up issue. However, we haven't been able to get any log information. We can get logs statements from the app code (in `main.dart` but shortly after the app boots (I am assuming when it is initializing plugins or something) it crashes.

We will look into trying to recreate in a new, fresh flutter application but I wanted to make a comment now in case anyone has figured the issue out.

iOS simulator and hardware work as expected. However, Android emulator and hardware crash at startup.

We'll try to get some more info soon.

**Comment by norm-140309** [comment] 2018-09-01 02:57
I am also experiencing exactly what ashtonthomas described.  It works on my iOS simulator, but Android fails every time.

You can create a fresh  flutter app, add the plugin to the pubspec.yaml file, clear out the main.dart file, paste in the example code from https://pub.dartlang.org/packages/stripe_payment#-example-tab-

Then try to run it in the Android emulator via "flutter run -d Android".  It crashes upon startup every time.

Plugin works wonderfully in iOS.  I look forward to seeing it run on my Android devices.

Thank you for your efforts Jonas.

**Comment by norm-140309** [comment] 2018-09-02 22:13
@ashtonthomas   Your suggest worked beautifully on my test app.  

Thank you for posting your findings!

**Comment by jonasbark** [comment] 2018-09-11 19:56
Closing this as it seems to be caused by not using FlutterFragmentActivity.

**Closed by jonasbark** 2018-09-11 19:56 UTC
