### ISSUE TITLE
Authenticate as connected account in the client 

### ISSUE THREAD

**Issue by macmatrix** [jonasbark/flutter_stripe_payment#94] opened 2019-11-12 16:13 UTC
Hi @jonasbark I am using your plugin and I managed to make it work under certain scenarios. I am able for example to completely process payment using Payment Intent. I am also able to do payment Intent using Stripe connect using transfer_data but I am struggling to implement direct charges to connected account. The issue I have is that I am not able to authenticate IN THE CLIENT as a connected account. Is there any way to `StripePayment.authenticatePaymentIntent` with a connected account? This is the link in case of stripe.js [(https://stripe.com/docs/stripe-js/reference#stripe-function)]. Thanks

**Comment by jonasbark** [comment] 2019-11-12 16:16
https://github.com/jonasbark/flutter_stripe_payment/pull/78
Is it related to this functionality by any chance?

**Comment by macmatrix** [comment] 2019-11-12 16:50
Hello, yes absolutely. I am so glad to see this is a work in progress. When do you think it will be available??? Many thanks and well done for the plugin !

**Comment by jonasbark** [comment] 2019-11-13 16:03
You can already try it out if you use the dev branch:
https://dart.dev/tools/pub/dependencies#git-packages

If it works for you, I'll publish a new version 👍

**Comment by macmatrix** [comment] 2019-11-13 19:47
Sure I can try it out but I am relatively new to flutter. Can you confirm what should I add in my yaml file?

**Comment by jonasbark** [comment] 2019-11-15 02:08
Look closely to the docs I mentioned:
![image](https://user-images.githubusercontent.com/1151304/68911407-df856300-078f-11ea-95c9-f732824105da.png)
Hint: Indention is important.

**Comment by jonasbark** [comment] 2019-11-15 12:37
https://github.com/jonasbark/flutter_stripe_payment/pull/78/files#diff-4eba0340d2676167d4256fe20e9c04baR141

**Comment by macmatrix** [comment] 2019-11-15 23:55
Thank you @jonasbark. 

I have tested successfully with Android emulator with both `StripePayment.paymentRequestWithCardForm()` and  `StripePayment.paymentRequestWithNativePay(androidPayOptions: AndroidPayPaymentRequest())`. Note I had to juggle around a bit and make it work only with setting `StripePayment.setStripeAccount(null);` before creating the payment method and then adding `StripePayment.setStripeAccount(acct_an_account);` after the payment intent was created and before the `StripePayment.authenticatePaymentIntent()`. I do not know if this was your original intent but add the stripe account before the PM did not create a valid PM.

I also tested with iOS but no luck there with simulator and real device. 

If you have any suggestion on alternative ways to make it work I am happy to try it out.

Thanks

**Comment by nicowernli** [comment] 2019-11-18 09:05
Hi @macmatrix , what's the error in iOS? I have it running on an iPhone X and an iPod touch with no issues. What iOS version are you using?

To make it work I just followed the official documentation: https://stripe.com/docs/connect/direct-charges#direct-intents

This returns a payment intent, so I change to the connected account just before the `StripePayment.confirmPaymentIntent(paymentIntent);`

I create the PM in the main account because I don't want to create them in every single connected account. So what I do is clonning the payment method just before using it.

**Comment by macmatrix** [comment] 2019-11-18 22:59
@nicowernli 

Here is my workflow (I use the 'manual' process as opposite to you)
1-    in the client: `setStripeAccount(null)`
2-    in the client: `paymentRequestWithNativePay` + `createPaymentMethod` using token  (or `createPaymentMethod`  with `CardFormPaymentRequest`)
3-    In the client: pass PM to server with an http request
4-    in the server: clone PM with a named stripe connected account & create payment intent $ and send PI back to client
4-    in the client: `setStripeAccount` to that stripe connected account
5-    `authenticatePaymentIntent`

I use a real iPhone 8 plus with iOS13.1 and a simulator iPhone 11 Pro max2006tr-00@yahoo.com iOS13.0.

Here are the errors

iPhone 8
I guess it does not like `setStripeAccount(null)` since it throwing a SIGABRT error. Here is the error log from swift
```
2019-11-18 22:08:20.526343+0000 Runner[17788:6516244] -[NSNull length]: unrecognized selector sent to instance 0x1ded139a0
2019-11-18 22:08:20.528270+0000 Runner[17788:6516244] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x1ded139a0'
*** First throw call stack:
(0x1a20e498c 0x1a1e0d0a4 0x1a1fe843c 0x1a20e8e08 0x1a20eabec 0x1a54ab47c 0x1a53a2db4 0x1a533d470 0x1078aef6c 0x1a2131ea4 0x1a1fbd224 0x1078aee90 0x1078b8f2c 0x1078b8d5c 0x1078af86c 0x1078abdac 0x108bf00b0 0x1b8d88e1c 0x108c61828 0x108c62c04 0x108c70c64 0x1a20623c4 0x1a205d3b8 0x1a205c8bc 0x1abec7328 0x1a60f16d4 0x102980f48 0x1a1ee7460)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

iPhone 11
In the simulator I manage to pass the the `setStripeAccount(null)` but the Payment Intent does not get confirmed. I talked to the stripe support team and they told me that the PaymentIntent lives on a connected account, but I am confirming it on my platform account so that's not working. This means that `setStripeAccount` on the account before `authenticatePaymentIntent` does not work and does not initialize the connected account in flutter...

I also provide examples of android requests which managed to succeed and in that case (using the same workflow in flutter which does not work for iOS)they told me these requests use the right publishable key but it *also* sets the connected account id in the `Stripe-Account` header. This means flutter manage to setStripeAccount properly for android

I am really keen to make it work so I look forward to any direction you will provide. Thanks !!

**Comment by nicowernli** [comment] 2019-11-20 08:34
OK, I can tell you my flow that works in both platforms.

1. in the client: `setStripeAccount(null)`
2. in the client: `createPaymentMethod`
3. in the client: POST to the server to create a Payment Intent.
4. in the server: I clone the PM, create a payment intent and set the StripeAccount to the connected account.
5. in the client: `setStripeAccount(CONNECTED_ACCOUNT)`
6. in the client: `confirmPaymentIntent(PAYMENT_INTENT_SECRET_KEY)`
7. in the client: Once the payment intent is confirmed I `setStripeAccount(null)` null just in case.

This is actually working in both Android (minSDK 21) and iOS (platform 10.1).

**Comment by macmatrix** [comment] 2019-11-20 09:09
Ok you are using the automatic process. I will try to do the same and see if I can replicate it. If not it mean I have a bug somewhere. If yes it mean this only works with the automatic process and not with the manual one. 

Thanks for the feedback and I will post asap

**Comment by macmatrix** [comment] 2019-11-22 10:29
@nicowernli are you using `StripePayment.paymentRequestWithNativePay()` in your step nr 2? I am not even able to create a token in the client with native pay. See my code below and the error from Xcode

```
    StripePayment.setStripeAccount(null);
    double amount = 10.4;
    List<ApplePayItem> items = [];

    items.add(ApplePayItem(
      label: 'some_name',
      amount: amount.toString(),
    ));

    StripePayment.paymentRequestWithNativePay(
      androidPayOptions: AndroidPayPaymentRequest(
        total_price: amount.toStringAsFixed(2),
        currency_code: 'GBP',
      ),
      applePayOptions: ApplePayPaymentOptions(
        countryCode: 'GB',
        currencyCode: 'GBP',
        items: items,
      ),
    ).then((token) async {
      //do something
    });
```

Here is my breakpoint in Swift in the STPAPAClient.m file of the stripe pod

> '- (NSMutableURLRequest *)configuredRequestForURL:(NSURL *)url {
>     NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:url];
>     [[self defaultHeaders] enumerateKeysAndObjectsUsingBlock:^(NSString *  _Nonnull key, NSString *  _Nonnull obj, __unused BOOL * _Nonnull stop) {
>         [request setValue:obj forHTTPHeaderField:key]; //**Issue is here**
>     }];
>     return request;
> }

Again Android is fine and I can process direct charges but not with iOS

**Comment by macmatrix** [comment] 2019-11-26 08:47
@nicowernli do you have any view on this? Does the error mean that Apple Pay does not allow to setStripeAccount to null?

**Comment by nicowernli** [comment] 2019-11-26 12:03
I'll be implementing Apple Pay in my own application these days so I'll come back with some feedback probably next week

**Comment by macmatrix** [comment] 2019-11-26 15:21
Ok I will wait diligently!

**Comment by nicowernli** [comment] 2019-11-27 16:12
@macmatrix did you make it work before this change? I installed version 1.0.5 (without my change) and Apple Pay crashed the app too.

I'm going to keep looking at it, but I'm sure that `setStripeAccount` is not the problem here.

**Comment by macmatrix** [comment] 2019-11-27 17:36
Yes it worked before the setStripeAccount  change. It is also working now if I use payment intent and destination charge. It does not work if I use payment intent and direct charges

**Comment by macmatrix** [comment] 2019-11-30 15:54
@nicowernli did you managed to make it work? Do you need to make nativePay work? I am happy to work together on it if you want

**Comment by nicowernli** [comment] 2019-12-02 09:02
@macmatrix I'm working on it, I had the same issues as you, app crashes when trying to open the native payment screen on ios

**Comment by nicowernli** [comment] 2019-12-02 10:20
I'm having many issues launching the app in xcode for debugging at this moment. Not sure whats going on

**Comment by nicowernli** [comment] 2019-12-02 11:21
I'm also having this issue:
https://github.com/jonasbark/flutter_stripe_payment/issues/102

**Comment by nicowernli** [comment] 2019-12-06 09:43
So debugging ios code I can find that this code is the one that fails:

```
# Pods/Stripe/STPAPIClient.m

- (NSMutableURLRequest *)configuredRequestForURL:(NSURL *)url {
    NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:url];
    [[self defaultHeaders] enumerateKeysAndObjectsUsingBlock:^(NSString *  _Nonnull key, NSString *  _Nonnull obj, __unused BOOL * _Nonnull stop) {
        [request setValue:obj forHTTPHeaderField:key];
    }];
    return request;
}
```
The trace is the following:

```
2019-12-06 10:40:25.298273+0100 Runner[23567:3357880] -[NSNull length]: unrecognized selector sent to instance 0x7fff80615710
2019-12-06 10:40:25.301875+0100 Runner[23567:3357880] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x7fff80615710'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c6ff94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c53dac ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c55f38 _CF_forwarding_prep_0 + 120
	5   CFNetwork                           0x00007fff22f50877 _CFHTTPServerResponseEnqueue + 42815
	6   CFNetwork                           0x00007fff22e47dd1 _CFStreamErrorFromCFError + 7283
	7   CFNetwork                           0x00007fff22ddd2e8 CFURLRequestSetHTTPHeaderFieldValue + 114
	8   Stripe                              0x0000000104603916 __40-[STPAPIClient configuredRequestForURL:]_block_invoke + 134
	9   CoreFoundation                      0x00007fff23cd7c37 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	10  CoreFoundation                      0x00007fff23cb2d5e -[__NSFrozenDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 222
	11  Stripe                              0x000000010460382e -[STPAPIClient configuredRequestForURL:] + 222
	12  Stripe                              0x000000010460d4a5 +[STPAPIRequest postWithAPIClient:endpoint:parameters:deserializers:completion:] + 341
	13  Stripe                              0x000000010460d28e +[STPAPIRequest postWithAPIClient:endpoint:parameters:deserializer:completion:] + 334
	14  Stripe                              0x0000000104604257 -[STPAPIClient createTokenWithParameters:completion:] + 1351
	15  Stripe                              0x0000000104600aec -[STPAPIClient(ApplePay) createTokenWithPayment:completion:] + 268
	16  stripe_payment                      0x00000001049adeb4 -[StripeModule paymentAuthorizationViewController:didAuthorizePayment:completion:] + 324
	17  PassKit                             0x00007fff2a6d72a2 __100-[PKPaymentAuthorizationViewController paymentAuthorizationCoordinator:didAuthorizePayment:handler:]_block_invoke + 247
	18  libdispatch.dylib                   0x0000000105408dd4 _dispatch_call_block_and_release + 12
	19  libdispatch.dylib                   0x0000000105409d48 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x0000000105417de6 _dispatch_main_queue_callback_4CF + 1500
	21  CoreFoundation                      0x00007fff23bb1df9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	22  CoreFoundation                      0x00007fff23baca59 __CFRunLoopRun + 2329
	23  CoreFoundation                      0x00007fff23babe16 CFRunLoopRunSpecific + 438
	24  GraphicsServices                    0x00007fff38438bb0 GSEventRunModal + 65
	25  UIKitCore                           0x00007fff4784fb48 UIApplicationMain + 1621
	26  Runner                              0x000000010209de6b main + 75
	27  libdyld.dylib                       0x00007fff51a1dc25 start + 1
	28  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by nicowernli** [comment] 2019-12-06 10:58
@macmatrix I think I found the issue, I'm workin in a fix right now.

**Comment by macmatrix** [comment] 2019-12-12 00:08
@nicowernli how is this going? Any luck to fix the Apple Pay crash?

**Comment by nicowernli** [comment] 2019-12-12 09:11
The fix has been merged to dev

**Comment by macmatrix** [comment] 2019-12-12 23:23
@nicowernli sorry for the noob question but what does it mean that the fix has been merged to dev?

**Comment by jonasbark** [comment] 2019-12-13 12:25
That the Pull Request was merged - I also updated the plugin version itself on pub.dev

**Comment by macmatrix** [comment] 2019-12-13 13:24
@jonasbark thanks, I have seen there is a version 1.0.6
Does this mean that the Apple Pay does not crash anymore with `setStripeAccount(null)`?

**Comment by macmatrix** [comment] 2019-12-13 16:02
@jonasbark @nicowernli I have used version 1.0.6 in my app and it all works well!! Many thanks for all you work!!

I am planning to use this plugin in a production append it is great I now can do direct charges with all payment methods !!

**Closed** 2019-12-13 17:00 UTC
